AWSTemplateFormatVersion: 2010-09-09
Description: This template is for FrontENd and BackEnd Loand Balancer
Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources: 
#-----------------------------------------
  # Ventura Prod ELB:ALB(FrontEnd/BackEnd), LB Listeners and Target Group
  #-----------------------------------------
  # Application/Internet-Facing/FrontEnd Loadbalancer
  VenturaProdFrontEndWebLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: FrontEndLB
      Subnets:
        - !ImportValue VenturaProdNATalbSN1idOutput
        - !ImportValue VenturaProdNATalbSN2idOutput
      SecurityGroups:
        - !ImportValue VenturaProdFrontEndLBSecurityGroupidOutput
      Tags:
        - Key: Name
          Value: VenturaProdFrontEndWebLB

  VenturaProdFrontEndLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref VenturaProdFrontEndWebLB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref VenturaProdFrontEndWebLBtg

  VenturaProdFrontEndWebLBtg: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: VenturaProdFrontEndWebLBtg
      VpcId: !ImportValue VenturaProdVPCidOutput
      Port: 80
      Protocol: HTTP
      TargetType: instance
      Targets: 
        - Id: !ImportValue VenturaProdWebServer1idOutput
          Port: 80
        - Id: !ImportValue VenturaProdWebServer2idOutput
          Port: 80

  # Application/Internal/BackEnd Loadbalancer
  VenturaProdBackEndAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: BackEndLB
      Scheme: internal
      Subnets:
        - !ImportValue VenturaProdAppSN1idOutput
        - !ImportValue VenturaProdAppSN2idOutput
      SecurityGroups:
        - !ImportValue VenturaProdBackEndLBSecurityGroupidOutput
      Tags:
        - Key: Name
          Value: VenturaProdBackEndAppLB

  VenturaProdBackEndAppLBtg: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: VenturaProdBackEndAppLBtg
      VpcId: !ImportValue VenturaProdVPCidOutput
      Port: 80
      Protocol: HTTP
      TargetType: instance
      Targets: 
        - Id: !ImportValue VenturaProdAppServer1idOutput
          Port: 80
        - Id: !ImportValue VenturaProdAppServer2idOutput
          Port: 80
  
  VenturaProdBackEndAppLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref VenturaProdBackEndAppLB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref VenturaProdBackEndAppLBtg